### ISSUE TITLE
[Video / Request]: Allow for custom video platforms/sources

### ISSUE THREAD

**Issue by Agenda2029** [archetyped/simple-lightbox-extensions#106]
## Description of feature/request
Very happy with how simple lightbox works. Not so happy though with the limitation only to youtube and vimeo. 
Would't it be possible to have a third custom option where one can fill out the video source.

## This feature would be used for
the option opening any video in a lightbox by clicking a link (either text or image)
I imagine with an added "simple-lightbox" class.
Thank you.

**Comment by archetyped** [comment]
Hi, unfortunately video platforms frequently have completely different implementations for loading their videos, so there is no catch-all solution to supporting all platforms.

I've created a [forum post for discussing platform support](https://github.com/archetyped/simple-lightbox-extensions/discussions/108) so that support for the most requested platforms can be prioritized.
